version: "3.9"

services:
  user-db-container:
    image: mysql
    container_name: user-db
    ports:
      - "8012:3306"
    volumes:
      - ./user-service/init/user.sql:/docker-entrypoint-initdb.d/user.sql
    environment:
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot
      MYSQL_ROOT_PASSWORD: nonroot
      MYSQL_DATABASE: user
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "8012"]
      timeout: 120s
      retries: 10
    networks:
      - mynet
  exercise-db-container:
    image: mysql
    container_name: exercise-db
    ports:
      - "8011:3306"
    volumes:
      # - ./exercise-service/init/exercise_local.sql:/docker-entrypoint-initdb.d/exercise.sql
      - ./exercise-service/init/exercise_microservice.sql:/docker-entrypoint-initdb.d/exercise.sql
    environment:
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot
      MYSQL_ROOT_PASSWORD: nonroot
      MYSQL_DATABASE: exercise
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "8011"]
      timeout: 120s
      retries: 10
    depends_on:
      user-db-container:
        condition: service_healthy
    networks:
      - mynet
  user-container:
    build:
      context: .
      dockerfile: ./user-service/deployment/user-service.Dockerfile
    container_name: user-api
    ports:
      - "8002:8080"
    depends_on:
      user-db-container:
        condition: service_healthy
    networks:
      - mynet
  exercise-container:
    build:
      context: .
      dockerfile: ./exercise-service/deployment/exercise-service.Dockerfile
    container_name: exercise-api
    ports:
      - "8001:1234"
    depends_on:
      exercise-db-container:
        condition: service_healthy
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
