version: "3.9"

services:
  db-container:
    image: mysql
    container_name: exercise-db
    ports:
      - "3306"
    volumes:
      - ./exercise-service/course.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot
      MYSQL_ROOT_PASSWORD: nonroot
      MYSQL_DATABASE: course2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 120s
      retries: 10
    networks:
      - mynet
  user-container:
    build:
      context: .
      dockerfile: user.Dockerfile
    container_name: user-api
    ports:
      - "8002:8080"
    depends_on:
      db-container:
        condition: service_healthy
    networks:
      - mynet
  exercise-container:
    build:
      context: .
      dockerfile: exercise.Dockerfile
    container_name: exercise-api
    ports:
      - "8001:1234"
    depends_on:
      db-container:
        condition: service_healthy
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
